services:
  fiber-app:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - app-network
    volumes:
      - grafana-storage:/var/lib/grafana  

  k6:
    image: grafana/k6
    command: [ "run", "-" ]
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes:
  grafana-storage: